### PR TITLE
Puppet4 compatibility

### PR DESCRIPTION
**Pull request by fschaer**
I have the module working for site/subsite/top bdii under a puppet4 server

### CODE REVIEW

**Comment by traylenator** [comment]
I'll try and bring this back to life. It's very overdue.

**Comment by fschaer** [comment]
I might have other changes since we now migrated to puppet 5 ;)

I’ll share my eventual changes once you’re done with the backlog…

**Comment by traylenator** [comment]
Okay so I just did an auto publication from here to puppetforge of a no change 0.2.1 release.
If you can rebase this I'll  get it merged.

**Comment by andrea-manzi** [comment]
Hey,
i have merged this PR with the PR #17 which have the travis tests from Steve, at https://github.com/cernops/puppet-bdii/tree/fschaer-puppet4.

i have fixed some lint errors but i still had an error with the tests..

https://travis-ci.org/cernops/puppet-bdii/jobs/305829912

loglevel is a metaparam; this value will inherit to all contained resources in the bdii::config definition

we we can simply rename that var..but we will break whoever is using it.

so for now i have disabled the tests.

I tested the deployment of a resource bdii and it's fine. i think Frederic has already tested the site and top bdii so  i think i will merge it and release to puppetforge. If there are then other changes due to P5 we can release them later.
cheers
Andrea

**Comment by fschaer** [comment]
Perfect :]

**Pull request merged**
